In [1]:
!git clone https://github.com/AkihisaNomoto/thermoreceptormodel.git

Cloning into 'thermoreceptormodel'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 75 (delta 28), reused 64 (delta 17), pack-reused 0
Receiving objects: 100% (75/75), 258.90 KiB | 3.98 MiB/s, done.
Resolving deltas: 100% (28/28), done.

In [3]:
%cd thermoreceptormodel

/content/thermoreceptormodel

In [4]:
import pandas as pd
import configuration
from thermoreceptormodel import model

#--------------------------------------
# Example 1 (Environmental step-change)
#--------------------------------------
# Create instance
model_instance = model.ThermoreceptorModel()

# Set parameters (you can use some parameters using setter method (ex. XXX.Y))
model_instance.T_core = 34
model_instance.hr = 5

# Set environmental parameters using add_phase method
model_instance.add_phase(duration_in_sec=60, t_db=25, t_r=25, q_irradiance=0)
model_instance.add_phase(duration_in_sec=60, t_db=30, t_r=30, q_irradiance=0)

# Define simulation results
df_simulation_results = model_instance.simulate(show_input=False)

# Output as a csv file
df_simulation_results.to_csv("example_simulation_1.csv")

In [5]:
df_simulation_results

,Version,Current_Time,dt,T_0,T_1,T_2,T_3,T_4,T_5,T_6,...,T_31,T_32,T_33,T_34,T_35,T_warm,dT_warm,R_warm,dR_warm,PSI
0,0.1.1,0.0,0.05,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,NaN,NaN,NaN,NaN
1,0.1.1,1.0,0.05,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,33.997601,33.993069,33.982586,33.961721,33.925791,33.991322,-0.000434,1.496666,NaN,NaN
2,0.1.1,2.0,0.05,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,33.986951,33.975228,33.956101,33.927144,33.886328,33.972040,-0.000964,0.864322,-0.632344,NaN
3,0.1.1,3.0,0.05,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,33.972175,33.955139,33.930799,33.897664,33.854590,33.951082,-0.001048,0.728515,-0.135807,NaN
4,0.1.1,4.0,0.05,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,33.957318,33.936685,33.909103,33.873533,33.829213,33.932088,-0.000950,0.800494,0.071979,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,0.1.1,116.0,0.05,33.993745,33.981221,33.968651,33.956007,33.943260,33.930382,33.917347,...,33.502454,33.482288,33.461909,33.441322,33.420530,33.478892,-0.000027,0.927305,-0.001573,NaN
117,0.1.1,117.0,0.05,33.993707,33.981106,33.968461,33.955744,33.942925,33.929980,33.916880,...,33.501884,33.481734,33.461368,33.440790,33.420006,33.478339,-0.000028,0.925750,-0.001556,NaN
118,0.1.1,118.0,0.05,33.993669,33.980994,33.968276,33.955486,33.942599,33.929586,33.916424,...,33.501306,33.481172,33.460818,33.440251,33.419473,33.477780,-0.000028,0.924211,-0.001539,NaN
119,0.1.1,119.0,0.05,33.993633,33.980885,33.968094,33.955235,33.942280,33.929202,33.915978,...,33.500723,33.480603,33.460262,33.439703,33.418932,33.477213,-0.000028,0.922688,-0.001523,NaN
120,0.1.1,120.0,0.05,33.993597,33.980778,33.967917,33.954990,33.941968,33.928827,33.915542,...,33.500134,33.480028,33.459698,33.439149,33.418383,33.476640,-0.000029,0.921181,-0.001507,NaN